Fix compile error on qemux86
:Release Notes:
Fix compile error on qemux86

:Detailed Notes:
Missing DEFAULT_SINK for qemux86
| ../git/gst/unifiedsinkbin/gstunifiedsinkbin.c:389:75: error: expected ')' before 'DEFAULT_SINK'
|   389 |         GST_DEBUG_OBJECT(unifiedsinkbin, "Sink element not created, try " DEFAULT_SINK);

| ../git/gst/unifiedsinkbin/gstunifiedsinkbin.c:473:20: error: 'DEFAULT_SINK' undeclared (first use in this function)
|   473 |        sink_name = DEFAULT_SINK;

:Testing Performed:
N/A

:QA Notes:
N/A

:Issues Addressed:
N/A

Change-Id: Ifa1f71bec3523f1be605450e0c8062b6cf646488
Reviewed-on: http://gpro.lge.com/c/webosose/gst-plugins-webos/+/349259
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Jimmy Ohn <yongjin.ohn@lge.com>
Tested-by: Jimmy Ohn <yongjin.ohn@lge.com>